server:
  port: 9999
  context-path: /

security:
  user:
    name: duke
    password: duke
  basic:
    enabled: false

management:
  security:
    enabled: false
  context-path: /management

logging:
  file: ./logs/gateway.log
  level: debug

zuul:
  retryable: true #开启zuul的重试，默认为false
  routes:
    duke-blog:
      url: http://127.0.0.1:1111/
      path: /api/blog/**
