server:
  port: 9999
  context-path: /

security:
  user:
    name: duke
    password: duke
  basic:
    enabled: true

management:
  security:
    enabled: false
  context-path: /management

logging:
  file: ./logs/gateway.log
  level: debug