spring:
  profiles:
    active: @profileActive@
security:
  user:
    name: duke
    password: duke
  basic:
    enabled: false
  oauth2:
    resource:
      service-id: duke-auth
      user-info-uri: http://dukehu.top:5285/user


management:
  security:
    enabled: false
  context-path: /management

logging:
  file: ./logs/gateway.log
  level: debug
debug: true

duke:
  swagger:
    enabled: true #开启swagger,默认为开启
    title: gateway api
    description: 网关项目服务
    version:
    termsOfServiceUrl:
    license:
    licenseUrl:
    basePackage: com.duke.framework.gateway